spring:
  profiles:
    active: prod

---
spring:
  profiles: dev

server:
  port: 6001

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: htpp://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost

---

spring:
     profiles: prod

server:
  port: 6002
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: htpp://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost  
  
