spring:
  profiles:
    active: prod

---

server:
  port: 7001


spring:
  application:
    name: product-prod-bus
  profiles: prod

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:6002/eureka

---
server:
  port: 7002


spring:
  application:
    name: product-dev-bus
  profiles: dev

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:6002/eureka
